version: "3.8"

services:
  database:
    container_name: postgresDB
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data


  mongo:
    container_name: mongoDB
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pg
      - MONGO_INITDB_ROOT_PASSWORD=123
      - MONGO_DB=mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/postgresql/data



volumes:
  postgres:
  mongo: